name: main

on: [ "workflow_dispatch", "push" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Docker build
        run: docker build -t gha-image:latest .

      - name: Taging a Docker image
        run: |
          docker tag gha-image:latest dev1232121/docker-github:$GITHUB_RUN_NUMBER
          
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.devkuk123 }}
          password: ${{ secrets.1234567890 }}
      
      - name: Docker push
        run: docker push dev1232121/docker-github:$GITHUB_RUN_NUMBER
