name: main

on: [ "workflow_dispatch", "push" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Docker build
        run: docker build -t gha-image:latest .

      - name: Tagging a Docker image
        run: |
          docker tag gha-image:latest devkuk123/docker-github:${GITHUB_RUN_NUMBER}
          
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      
      - name: Docker push
        run: docker push devkuk123/docker-github:${GITHUB_RUN_NUMBER}

